#!/bin/bash
#
# a simple dmenu session script 
#
###

DMENU='dmenu -i -fn -xos4-terminus-medium-r-*--12-*-*-*-*-*-iso10646-1'
choice=$(echo -e "logout\nshutdown\nreboot\nsuspend\nhibernate" | $DMENU)

case "$choice" in
  logout) i3-msg exit & ;;
  shutdown) sudo shutdown -h now & ;;
  reboot) sudo shutdown -r now & ;;
  suspend) systemctl suspend & ;;
  hibernate) systemctl hibernate & ;;
esac
